#!/bin/bash

# etcd - Startup script for etcd

# chkconfig: 35 83 15
# description: App for Hydra persistence 
# processname: etcd
# config: 
# pidfile: /var/run/etcd.pid

APP_NAME=etcd
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/forever.sh
DAEMON_ARGS="/opt/etcd/etcd -config /etc/etcd/etcd.conf"
RUNDIR=/opt/etcd
USER=hydra
GROUP=hydra
PID_DIR=/var/run
PID_NAME=$APP_NAME.pid
PID_FILE=$PID_DIR/$PID_NAME
LOCK_FILE=/var/lock/subsys/${APP_NAME}
LOG_FILE=/var/log/${APP_NAME}/${APP_NAME}.log

case "$1" in
start)
  if [ -f $PID_FILE ]
  then
    echo Already running with PID `cat $PID_FILE`
  else
    rm -rf $RUNDIR/log $RUNDIR/info $RUNDIR/conf $RUNDIR/snapshot
    if [ ! -d /var/log/${APP_NAME} ]; then
      sudo mkdir /var/log/${APP_NAME}
    fi
    sudo chown -R $USER:$GROUP /var/log/${APP_NAME}
    cd $RUNDIR
    sudo -u "$USER" $DAEMON $DAEMON_ARGS &>$LOG_FILE &
    RETVAL=$?
    if [ $RETVAL -eq 0 ]
    then
      echo [OK]
      PID=$!
      touch $LOCK_FILE
      echo $PID > $PID_FILE
    else
      echo [ERROR]
    fi
  fi
  ;;
stop)
  if [ -f $PID_FILE ]
  then
  	if [ -f ${PID_FILE} ]; then
      kill -9 `ps -ef | grep "$DAEMON_ARGS" | awk '{print $2}'`
      rm -f $LOCK_FILE
      rm -f $PID_FILE 
    else
      echo $PID_FILE not found
    fi
  fi
  ;;
restart)
  ${0} stop
  ${0} start
  ;;
*)
  echo "Usage: /etc/init.d/$APP_NAME {start|stop|restart}"
  exit 1
  ;;
esac

exit 0