#!/bin/bash

# hydra_server_api - Startup script for hydra server api

# chkconfig: 35 84 15
# description: App for hydra server api
# processname: node
# config: 
# pidfile: /var/run/hydra_server_api.pid

APP_NAME=hydra_server_api
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/forever.sh
DAEMON_ARGS="node /opt/hydra_server/src/server_api/app/main.js --port=8443 --env=pro"
RUNDIR=/opt/hydra_server/src
USER=hydra
GROUP=hydra
PID_DIR=/var/run
PID_NAME=$APP_NAME.pid
PID_FILE=$PID_DIR/$PID_NAME
LOCK_FILE=/var/lock/subsys/${APP_NAME}
LOG_FILE=/var/log/${APP_NAME}/${APP_NAME}.log

case "$1" in
start)
  if [ -f $PID_FILE ]
  then
    echo Already running with PID `cat $PID_FILE`
  else
    if [ ! -d /var/log/${APP_NAME} ]; then
      sudo mkdir /var/log/${APP_NAME}
    fi
    sudo chown -R $USER:$GROUP /var/log/${APP_NAME}
    cd $RUNDIR
    sudo -u "$USER" $DAEMON $DAEMON_ARGS &>$LOG_FILE &
    RETVAL=$?
    if [ $RETVAL -eq 0 ]
    then
      echo [OK]
      PID=$!
      touch $LOCK_FILE
      echo $PID > $PID_FILE
    else
      echo [ERROR]
    fi
  fi
  ;;
stop)
  if [ -f $PID_FILE ]
  then
    if [ -f ${PID_FILE} ]; then
      kill -9 `ps -ef | grep "$DAEMON_ARGS" | awk '{print $2}'`
      rm -f $LOCK_FILE
      rm -f $PID_FILE 
  	fi
  else
    echo $PID_FILE not found
  fi
  ;;
restart)
  ${0} stop
  ${0} start
  ;;
*)
  echo "Usage: /etc/init.d/$APP_NAME {start|stop|restart}"
  exit 1
  ;;
esac

exit 0